name: agent_windows
description: Agente de monitoramento para Windows
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # HTTP e comunicação
  http: ^1.1.0
  shared_preferences: ^2.2.2
  flutter_background_service: ^5.0.0
  system_tray: ^2.0.3
  window_manager: ^0.5.1

  # Gerenciamento de Estado
  provider: ^6.1.2 
  
  # Injeção de Dependência
  get_it: ^9.0.5 
  
  # Logging e Utils
  logger: ^2.3.0
  path_provider: ^2.1.3
  intl: ^0.20.2
  path: ^1.9.0
  
  # UI/UX Dependencies
  google_fonts: ^6.1.0
  flutter_animate: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4 

flutter:
  uses-material-design: true
  
  assets:
    - assets/app_icon.ico
    - assets/logo.png
    - assets/scripts/

flutter_icons:
  windows:
    generate: true
    image_path: "assets/logo.png"